### ISSUE TITLE
Project Information

### ISSUE THREAD

**Issue by travismiller** [tulsaschoolsdata/tps-legacy-ecumulative-reports#1]
This issue describes and tracks progress of this project.

Project Meeting Notes: https://docs.google.com/document/d/1qMRyyk1qq1bi3EZ9GvoSHIsASlTP0H0axqOlNIduP4A

##TODO
- [ ] Finish Test Scores Tables
- [ ] Review with Justin and Jeana
- [ ] Establish plan for packaging for Scribbles
